version: '3.4'

services:
  api001:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ocelotgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

